version: '3.9'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./DB.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: servicios_catalogo
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    container_name: fastapi-db-catalogo

  fastapi:
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: servicios_catalogo
    build:
      context: ./API/
      dockerfile: Dockerfile
    container_name: fastapi-app-catalogo
    volumes:
      - ./:/API/
    ports:
      - "8000:8000"
    restart: always
