version: '3.9'

services:
  db-pedidos:
    image: mysql:8.0
    volumes:
      - ./DB.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: servicios_pedidos
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    container_name: db-pedidos

  fastapi-pedidos:
    depends_on:
      - db-pedidos
    environment:
      DB_HOST: db-pedidos
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: servicios_pedidos
    build:
      context: ./API/
      dockerfile: Dockerfile
    container_name: fastapi-pedidos
    volumes:
      - ./:/API/
    ports:
      - "8001:8000"
    restart: always
