version: '3.9'

services:
  db-notificacion:
    image: mysql:8.0
    volumes:
      - ./DB.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: servicios_notificaciones
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    container_name: db-notificacion

  fastapi-pedidos:
    depends_on:
      - db-notificacion
    environment:
      DB_HOST: db-notificacion
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: servicios_notificaciones
    build:
      context: ./API/
      dockerfile: Dockerfile
    container_name: fastapi-notificacion
    volumes:
      - ./:/API/
    ports:
      - "8002:8000"
    restart: always
